[book]
title = "Sea of Stars"
description = "The Huayu's Blogs"
authors = ["Huayu Zhang"]
language = "en"

[build]
create-missing = false

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/levihuayuzhang/levihuayuzhang.github.io"

[output.html.playground]
runnable = true
editable = true
copyable = true
line-numbers = true

[output.html.print]
enable = true
page-break = true
