[book]
title = "Sea of Stars"
authors = ["Huayu Zhang"]
description = "The Huayu's Blogs"
language = "en-US"
multilingual = true
src = "src"

[build]
create-missing = false

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/levihuayuzhang/levihuayuzhang.github.io"
git-repository-icon = "fa-github"

[output.html.playground]
runnable = true
editable = true
copyable = true
line-numbers = true

[output.html.print]
enable = true
page-break = true
